#page title
page_title                                : EstateSail - Professional Estate Sale Management                                    

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        

appstore_link                             :                                           # Will auto-populate when app is live
playstore_link                            :                                           
presskit_download_link                    :                                           

app_icon                                  : assets/appicon.png                      
app_name                                  : EstateSail                                           
app_price                                 : Free                                           
app_description                           : Transform your estate sale business with AI-powered appraisals and professional listing management.

enable_smart_app_banner                   : true                                      

# Screenshots
device_color                              : black
your_screenshot                           : yourscreenshot.png

# Information About Yourself
your_name                                 : EstateSail Team                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 

# Feature List                            
features                                  :

  - title                                 : AI-Powered Appraisals
    description                           : Leverage advanced AI technology to accurately appraise items and generate professional descriptions instantly.
    fontawesome_icon_name                 : robot
    
  - title                                 : Smart Photo Analysis
    description                           : Take photos of items and let our AI identify brands, materials, and key details automatically.
    fontawesome_icon_name                 : camera

  - title                                 : Professional Listings
    description                           : Create beautiful, detailed listings with measurements, conditions, and pricing optimized for maximum value.
    fontawesome_icon_name                 : tag

  - title                                 : E-commerce Integration
    description                           : Seamlessly sync your inventory with popular platforms like Shopify to expand your reach.
    fontawesome_icon_name                 : store

  - title                                 : Inventory Management
    description                           : Keep track of all your items, categories, and sales in one organized platform.
    fontawesome_icon_name                 : boxes
  
  - title                                 : Expert Insights
    description                           : Get valuable market insights and pricing recommendations based on extensive estate sale data.
    fontawesome_icon_name                 : chart-line

# Theme Settings
topbar_color                              : "#2C3E50"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    
cover_overlay_color                       : "#2C3E50"
cover_overlay_transparency                : 0.8

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#3498DB"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#2C3E50"
feature_text_color                        : "#34495E"

feature_icons_foreground_color            : "#3498DB"
feature_icons_background_color            : "#ECF0F1"

social_icons_foreground_color             : "#34495E"
social_icons_background_color             : "#ECF0F1"

footer_text_color                         : "#34495E"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
