#page title
page_title                                : EstateSail - Coming Soon                                    

# App Info
ios_app_id                                :                                
ios_app_country                           :                                        

appstore_link                             :                                           
playstore_link                            :                                           
presskit_download_link                    :                                           

app_icon                                  : assets/app-icon-new.png                      
app_name                                  : EstateSail                                           
app_price                                 : Coming Soon                                           
app_description                           : The future of estate sale management is coming. EstateSail will transform how you run estate sales with AI-powered appraisals and professional tools.

enable_smart_app_banner                   : false                                      

# Screenshots
device_color                              : black
your_screenshot                           : assets/screenshot/yourscreenshot.png

# Information About Yourself
your_name                                 : EstateSail Team                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 

# Feature List                            
features                                  :

# Theme Settings
topbar_color                              : "#2C3E50"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    
cover_overlay_color                       : "#2C3E50"
cover_overlay_transparency                : 0.8

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#3498DB"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#2C3E50"
feature_text_color                        : "#34495E"

feature_icons_foreground_color            : "#3498DB"
feature_icons_background_color            : "#ECF0F1"

social_icons_foreground_color             : "#34495E"
social_icons_background_color             : "#ECF0F1"

footer_text_color                         : "#34495E"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
