#page title
page_title                                : EstateSail                                    

# App Info
ios_app_id                                :                                
ios_app_country                           :                                        

appstore_link                             :                                           
playstore_link                            :                                           
presskit_download_link                    :                                           

app_icon                                  : assets/app-icon-new.png                      
app_name                                  : EstateSail                                           
app_price                                 :                                            
app_description                           : The future of estate sale management is coming. EstateSail will transform how you run estate sales with AI-powered appraisals and professional tools.

enable_smart_app_banner                   : false                                      

# Screenshots
device_color                              : black
your_screenshot                           : assets/screenshot/yourscreenshot.png

# Information About Yourself
your_name                                 : EstateSail Team                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 

# Feature List                            
features                                  :
  - title                                 : AI-Powered Inventory
    description                           : Instantly scan and catalog items using AI. Get automatic pricing recommendations based on real market data.
    fontawesome_icon_name                 : magic

  - title                                 : Seamless Estate Sale Management
    description                           : Manage your entire estate sale in one place—inventory, pricing, labeling, sales tracking, and fulfillment.
    fontawesome_icon_name                 : toolbox

  - title                                 : Smart Image Recognition
    description                           : Snap a photo, and our AI identifies, categorizes, and prices items in seconds—no manual data entry needed.
    fontawesome_icon_name                 : camera

  - title                                 : Live Sales Tracking & Reporting
    description                           : Track every sale in real-time, generate reports, and analyze performance instantly from your dashboard.
    fontawesome_icon_name                 : chart-line

  - title                                 : Integrated Barcode Labeling
    description                           : Generate and print barcode labels directly from the app, ensuring quick item lookup and seamless checkout.
    fontawesome_icon_name                 : barcode

  - title                                 : Online & In-Person Selling
    description                           : List items for sale online and in-person simultaneously, with automated fulfillment and nationwide shipping options.
    fontawesome_icon_name                 : shopping-cart

# Theme Settings
topbar_color                              : "#2C3E50"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    
cover_overlay_color                       : "#2C3E50"
cover_overlay_transparency                : 0.8

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#3498DB"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#2C3E50"
feature_text_color                        : "#34495E"

feature_icons_foreground_color            : "#3498DB"
feature_icons_background_color            : "#ECF0F1"

social_icons_foreground_color             : "#34495E"
social_icons_background_color             : "#ECF0F1"

footer_text_color                         : "#34495E"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
